{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "service-a.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-username: {{ required "Database username is required" .Values.secret.databaseUsername | quote }}
  database-password: {{ required "Database password is required" .Values.secret.databasePassword | quote }}
{{- end }}
