replicaCount: 2

image:
  repository: akshaygouda646/service-a
  tag: v1
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  host: service-a-qa.local

config:
  SPRING_PROFILES_ACTIVE: qa
  SERVICE_NAME: service-a

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m

secret:
  create: false
  name: service-a-qa-secret
