replicaCount: 2

image:
  repository: akshaygouda646/service-a
  tag: v1
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  host: service-a-qa.local

config:
  springProfile: qa
  applicationName: service-a
  serverPort: "8083"
  loggingLevel: INFO

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m

secret:
  create: false
  name: service-a-qa-secret
