replicaCount: 1

image:
  repository: akshaygouda646/service-a
  tag: v1
  pullPolicy: IfNotPresent

containerPort: 8083

service:
  type: ClusterIP
  port: 80
  targetPort: 8083

ingress:
  enabled: true
  className: nginx
  host: service-a.local
  path: /
  pathType: Prefix

deployment:
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

probes:
  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 40
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m

config:
  SPRING_PROFILES_ACTIVE: default
  SERVICE_NAME: service-a

secret:
  create: false
  name: service-a-secret
  databaseUsername: ""
  databasePassword: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL
