replicaCount: 1

image:
  repository: akshaygouda646/service-b
  tag: v1
  pullPolicy: IfNotPresent

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

service:
  type: NodePort
  port: 80
  targetPort: 8084
  nodePort: 30084

config:
  appName: service-b
  springProfile: dev

secret:
  name: service-b-secret
  databaseUsername: admin
  databasePassword: password

deployment:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

probes:
  readiness:
    path: /actuator/health/readiness
    initialDelaySeconds: 70
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 12

  liveness:
    path: /actuator/health/liveness
    initialDelaySeconds: 120
    periodSeconds: 15
    timeoutSeconds: 5
    failureThreshold: 3

podSecurityContext:
  runAsNonRoot: false

securityContext:
  runAsNonRoot: false
  allowPrivilegeEscalation: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

ingress:
  enabled: true
  className: nginx

  annotations: {}

  hosts:
    - host: service-b.local
      paths:
        - path: /
          pathType: Prefix

  tls: []