replicaCount: 3

image:
  repository: akshaygouda646/service-b
  tag: v1
  pullPolicy: Always

ingress:
  enabled: true
  host: service-b.example.com

config:
  SPRING_PROFILES_ACTIVE: prod
  SERVICE_NAME: service-b

resources:
  requests:
    memory: 512Mi
    cpu: 250m
  limits:
    memory: 1Gi
    cpu: "1"

secret:
  create: false
  name: service-b-prod-secret

