server:
  port: ${SERVER_PORT:8083}

spring:
  application:
    name: service-c

app:
  environment: ${APP_ENVIRONMENT:local}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

info:
  app:
    name: service-c
    version: 1.0.0
